pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo "test"
            }
        }
        stage('Test') {
            steps {
                echo "test"
            }
            
        }
        stage('Deliver') {
            steps {
                echo "test"
            }
        }
    }
}
