pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo "test1"
            }
        }
        stage('Test') {
             steps {
                echo "test2"
             }
        }
        stage('Deliver') {
           steps {
                echo "test3"
             }
        }
    }
}
